### ISSUE TITLE
name=value syntax should be spit by preprocessor 

### ISSUE THREAD

**Issue by jbee** [sormuras/command-line-interface#12]
When the name=value syntax is used this should be unified to two independent arguments

    "name=value" => "name" "value"

A good example why this makes more sense is this jar command:

    jar --create --date="2021-01-06T14:36:00+02:00" --file=classes.jar Foo.class Bar.class

the quoted value is just unquoted if the name=value syntax is already split.

**Comment by forax** [comment]
I've tried to look at that but the syntax "name=value" is driven by the type of the option,
- if the option is a flag, we allow
   name=true and name=false
- if the option is a single, we allow
   name=value
- if the option is a repeatable, we allow
   name=val1,val2,val3

This can not be implemented as a preprocessor, because a preprocessor does not have access to the type of an option

**Comment by forax** [comment]
Close as won't fix.
